### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#14]
1) Suppression du Bold
2) Menu Items
New Meal
Food
Report
..Meal Diary
..Insulin Overview
..Insulin Ratio
Settings
..Meals and Insulin
..Favourite Foods
..Food Cattegories
..Password lock
..Alerts
..Initial Setup
..Reset
Export
About GluCalc
..Terms of use

3) Disposer une icône à gauche des items principaux du menu Food, Report, Settings (autres icônes à trouver)

**Comment by jmottet** [comment]
Le menu - et ses sous-menu - a été implémenté. Les icônes ont aussi été ajoutés à gauche des items.
Ce cas peut être fermé.
