### ISSUE TITLE
Superposition des écrans

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#19]
Problème de gestion de l'affichage des écrans
Procédure pour reproduire le bug :

1. Lancer GluCalc

2. Sélectionner Menu Food
3. Sélection d'un aliment

4. Sélectionner Menu New Meal
5. Bouton back au bas de l'écran

-> Superposition de l'affichage de l'écran New Meal et de l'écran Food

**Comment by jmottet** [comment]
Correction effectuée.
