### ISSUE TITLE
New Meal - Ecran 1 - Corriger le libellé du 2ème champ

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#20]
Remplacer le libellé du champ "Carbohydrate" par le libellé "Blood glucose"

**Comment by jmottet** [comment]
Correction effectuée.

Par contre, est-ce qu'il faut garder le libellé "Glycemia" dans les écrans 2 & 3 ? Ou faut-il également écrire "Blood glucose" ?

**Comment by laurel1635** [comment]
1. Remplacer partout Glycemia par Blood glucose
2. Renseigner la valeur Blood glucose = Gliycémie dans le fichier de traduction pour que le texte correct apparaisse également en version française

**Comment by jmottet** [comment]
Ceci est corrigé pour les écrans 2 & 3 de la prise de repas.

Par contre, il reste 2 autres endroits :
* Edit Meal Type => "Glycemia target"
* Insulin Overview => "Glycema"

**Comment by jmottet** [comment]
A faire aussi dans les deux endroits mentionné ci-dessus.

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by laurel1635** [comment]
OK, il reste encore le libellé du 2ème champ de la version française qui est resté "Glucides" au lieu de Glycémie

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by jmottet** [comment]
Changer le "hint" avec le libellé suivant:
"Saisir une valeur de glycémie"

**Comment by laurel1635** [comment]
Adapter aussi la version anglaise
"Enter a blood glucose" -> "Enter a blood glucose value"

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by laurel1635** [comment]
OK
