### ISSUE TITLE
New Meal - Ecran 1 - Bouton On/Off

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#25]
Le libellé à droite du bouton ON/OFF est redondant avec le texte du bouton. 
Proposition : Supprimer le libellé et conserver uniquement le bouton

**Comment by jmottet** [comment]
Ce comportement semble est propre à la version 4.X d'Android.

En 5.X, le bouton ON/OFF ne contient pas de libellés.

Pour l'instant, on laisse comme ça.
