### ISSUE TITLE
New Meal - Ecran 1 - Next / Back

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#26]
Ce serait "Top" de pouvoir passer de l'écran 1 à l'écran 2, puis de l'écran 2 à l'écran 3 avec le glisser du pouce.

En revanche, la clôture du repas doit rester actionnable avec uniquement un bouton

**Comment by laurel1635** [comment]
Nice to have

**Comment by jmottet** [comment]
Solution implémentée de glisser du pouce pour passer de l'écran 1 -> 2 -> 3 de la prise de repas.
A valider.

**Comment by laurel1635** [comment]
Fonctionnement OK, mais dommage d'avoir supprimé le next dans la barre en haut à droite. Les deux sont complémentaires.

**Comment by jmottet** [comment]
En résumé, il y a 3 choses à corriger:
- Le mouvement "Right to Left" ne doit pas effectuer l'action "Back" mais ouvrir la page précédente (comme le "Next")
- Remettre les boutons "next"
- Pouvoir faire un "Back" en étant sur la liste d'aliment de l'écran 2

**Comment by jmottet** [comment]
Les 3 choses mentionnées sont corrigées.
