### ISSUE TITLE
Settings - Meals and Insulin

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#27]
Lors de l'affichage du clavier, la dernière ligne est à moitié masquée.
Selon les écrans, la ligne pourrait disparaître et empêcher la saisie
![screenshot_2015-10-27-20-41-00](https://cloud.githubusercontent.com/assets/8920509/10770483/cc05a890-7ceb-11e5-8736-0b1707b47eed.png)
![screenshot_2015-10-27-20-41-06](https://cloud.githubusercontent.com/assets/8920509/10770487/d1cc7ed4-7ceb-11e5-9834-0ec42bf1075f.png)

**Comment by laurel1635** [comment]
Pour résoudre le problème de l'affichage, utiliser le scroll de l'écran

**Comment by jmottet** [comment]
J'ai mis en place le système de scroll de l'écran pour :

- Edition d'un aliment
- Edition d'un repas & insuline

**Comment by laurel1635** [comment]
OK, parfait.
