### ISSUE TITLE
New Meal - Ecran 2 - Revue du design

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#31]
[GluCalc- New Meal - Ecran 2 - Design_V2 .pptx](https://github.com/jmottet/GluCalc/files/28436/GluCalc-.New.Meal.-.Ecran.2.-.Design_V2.pptx)

**Comment by jmottet** [comment]
Mettre la taille des polices à 13sp.

**Comment by jmottet** [comment]
- Mettre la taille des polices à 16sp (si cela convient)

**Comment by jmottet** [comment]
La taille des polices est désormais de 16sp. A voir si cela convient.

**Comment by jmottet** [comment]
Mettre toutes les pages à 16sp.

**Comment by jmottet** [comment]
Correction effectuée.
