### ISSUE TITLE
Terms of use - Introduire le texte

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#35]
TERM OF USE
In using GluCalc (the Application), you declare that you have understood and accepted the following disclaimer. If you do not accept these conditions you should not use the GluCalc application.

USE OF THE APPLICATION
The fees related to phone calls and internet connections while using the Application are to be fully borne by the user of the Application and can vary depending on the mobile network provider.

COPYRIGHT
The Application is protected by legislation related to copyright.

EXCLUSION OF WARRANTY AND COMPLETENESS OF INFORMATIONS
Although the author chooses and verifies information presented by GluCalc very carefully, neither the author, nor his partners can guarantee that information or software documents will always be up to date, accurate or exhaustive.

RESPONSIBILITY WAIVER
You are using the GluCalc application at your own risk. The Author cannot be held responsible for accidents or damages of any nature as a consequence of the use of the Application.
The Author cannot be held responsible for possible direct or indirect damages resulting from the use of information appearing on the Application or found on internet website accessed via the Application.
The Author cannot be hold responsible for any direct or indirect damages resulting from the access or use of (or from impossibility to access and use or from malfunctioning) the elements of the Application. The continuous and correct functioning of the mobile phone network and the Application cannot be guaranteed.
Persons establishing connection to internet websites do so at their own risk.

DATA PROTECTION
The application requires no personal data. However data transmission is not encrypted and therefore there is a risk that data could be lost and/or received by a third person. The author takes no responsibility regarding the safety of data transmission.

LAW TO BE APPLIED
All information or data, their use, the use of the Application and the present disclaimer subject to the Swiss law only.
The author reserves the right to modify at any time and without notice, the information or the data in the application as well as the disclaimer.

CONDITIONS GENERALES
En accédant à l’application GluCalc (ci-après : l’Application), vous déclarez avoir compris et accepter les conditions générales suivantes. Si vous n’acceptez pas les présentes conditions générales, vous devez renoncer à accéder à l’application GluCalc.

UTILISATION
Les frais de connexion au réseau téléphonique et internet relatifs à l’utilisation de l’Application sont évidemment à la charge des utilisateurs de l’Application et sont fonction des tarifs de l’opérateur mobile.

DROIT D’AUTEUR
L’Application est protégée par les dispositions légales relatives aux droits d’auteurs.

EXCLUSION DE GARANTIE – EXHAUSTIVITE DES INFORMATIONS
Bien que l’auteur vérifie et choisisse soigneusement les informations présentes sur l’Application GluCalc au moment de leur publication, ni l’auteur, ni ses éventuels partenaires ne sont en mesure de garantir que les informations, logiciels, documents ou autre renseignements transmis ou mis à disposition sont toujours d’actualité, exhaustifs ou exacts.

EXCLUSION DE RESPONSABILITE
Vous utilisez l’application GluCalc à vos propres risques et périls. La responsabilité de l’auteur ne saurait être engagée pour les accidents ou dommage de quelque nature que ce soit survenus durant l’utilisation de l’Application.
L’auteur ne peut en aucun cas être tenu responsable d’éventuels dommages directs ou indirects résultant de l’utilisation des informations figurant sur l’Application ou de l’accès à d’autres sites internet par le biais de liens existants.
En aucun cas l’auteur ne peut être tenu responsable pour tout dommage direct ou indirect résultant de l’accès et de l’utilisation (ou de l’impossibilité d’accéder et d’utiliser ou encore du mauvais fonctionnement) des éléments de l’Application. Ainsi notamment, le fonctionnement permanent et exempt de défaillance du réseau de téléphonie et de l’Application n’est pas garanti.
Les personnes établissant des liens vers des pages hors site ou vers d’autres sites internet agissent à leurs propres risques et périls.

PROTECTION DES DONNEES
L’application n’exige pas de données nominatives. Néanmoins, l’envoi des données n’étant pas crypté, il existe un risque que des données soient perdues et / ou reçues par des tiers. L’auteur décline en conséquence toute responsabilité concernant la sécurité de la transmission des données.

DROIT APPLICABLE
Toute information ou donnée, leur utilisation, l’utilisation de l’Application, ainsi que les présentes conditions générales sont soumises exclusivement au droit suisse.
L’auteur se réserve enfin le droit de modifier à tout moment et sans préavis les informations ou les données présentes sur son application, ainsi que les conditions générales.

**Comment by jmottet** [comment]
Implémentation effectuée.

**Comment by laurel1635** [comment]
OK
