### ISSUE TITLE
Définition d'un repas - information contextuelle sur les champs

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#38]
Repas & Insuline
1. Indiquer les unités de mesures pour chaque champ
2. Permettre l'affichage d'une information contextuelle sur chaque champ
(cf. capture d'écran, bouton i)
![img_0642](https://cloud.githubusercontent.com/assets/8920509/10831396/b1e5fcda-7e85-11e5-9c7e-60dba0d08284.PNG)

****************
"Type de repas"
"Ce champ définit le nom du repas. L’ajout d’un numéro devant le nom du repas permet de faire apparaître les repas dans la séquence désirée."

"Cible alimentaire"
"Ce champ définit en grammes, la quantité de glucides recommandée pour le repas."

"Cible de glycémie"
"Ce champ définit la valeur de glycémie souhaitée après le repas, exprimée dans l’unité de mesure choisie."

"Facteur de sensibilité à l'insuline"
"Le facteur de sensibilité est aussi appelé le facteur de correction. Il exprime la diminution de la valeur de glycémie lorsque 1 UI d’insuline est injectée. Cette valeur doit être définie dans la même unité de mesure que celle qui est sélectionnée dans GluCalc.\n\nLe facteur de sensibilité permet de calculer la dose d’insuline nécessaire pour atteindre la glycémie cible. Celle-ci est indépendante du repas et doit être valable sans apport de glucides."

"Insuline"
"Ce champ définit le besoin en insuline correspondant à 10 g de glucides ingérés au moment du repas."

****************

"Meal Type"
"This field defines the name of the meal. If you add a number before the name of the meal, you can sort the meal in order of numbers."

"Food target"
"Food target/Info" = "This field defines in grams, the recommended quantity of carbohydrates for the meal.";

"Blood Glucose Target"
"This field defines the wished blood glucose value after the meal, expressed in the selected unit.";

"Sensitivity Factor"
"The sensitivity factor is also named the correction factor. It expresses the reduction of the blood glucose value when 1 IU of insulin is injected. This value must be define in the same unit as the one selected in GluCalc.\n\nThe sensibility factor allows to calculate the necessary quantity of insulin to reach the target blood glucose. This quantity is separate of the meals insulin and must be valid even if no carbohydrates are ingested.";

"Insulin"
"This field define the requirement of insulin corresponding to 10 grams of carbohydrates ingested during the meal.";

**Comment by jmottet** [comment]
Lorsqu'on clique sur un bouton "I", on ouvre une pop-up avec bouton "OK".

**Comment by jmottet** [comment]
Implémentation effectuée.

**Comment by laurel1635** [comment]
Info contextuelle - OK
Il reste encore les unités de mesure pour chaque champ

**Comment by jmottet** [comment]
[g] => Fixe
[mmol/l] => Conifiguration/setup install
[UI /10 g] => selon la langue choisie

**Comment by jmottet** [comment]
Correction effectuée : Les unités de mesures ont été ajoutées.

**Comment by laurel1635** [comment]
OK pour les unités de mesures, 2 remarques : 

1) Aligner la valeur sur le texte du titre (cf. screenshot 1)
![capture2](https://cloud.githubusercontent.com/assets/8920509/13826947/5e0361c8-ebba-11e5-8fd8-e743680acb5f.PNG)

2) En raccourcissant le champ, le libellé du champ vide n'est plus visible entièrement (cf. screenshot 2)
Option 1 - supprimer le libellé
Option 2 - rallonger le champ
![capture1](https://cloud.githubusercontent.com/assets/8920509/13826921/3d177710-ebba-11e5-888b-484a25259842.PNG)

**Comment by laurel1635** [comment]
1) Maintenir la taille initiale du texte
2) Modifier les textes (cf. ci-dessous)
3) Ajuster les alignements du texte sur le titre (cf. ci-dessus)

Version française
- Type de repas > Saisir un type de repas (inchangé)
- Cible alimentaire > Saisir une valeur [g]
- Cible de glycémie > Saisir une valeur [mmol/l]
- Facteur de sensibilité à l'insuline > Saisir une valeur [mmol/l]
- Insuline > Saisir une valeur [UI/10g]

English version
- Meal type > Enter a meal type name (inchangé)
- Food targer > Enter a value [g]
- Blood glucose target > Enter a value [mmol/l]
- Sensivity factor > Enter a value [mmol/l]
- Insulin > Enter a value [IU/10g]

**Comment by jmottet** [comment]
Correction effectuée selon commentaires du 12/05/2016

**Comment by laurel1635** [comment]
Tiptop :-)
