### ISSUE TITLE
Définition d'un repas - Rotation de l'écran

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#39]
Lors de l'édition d'un repas (Settings \ Meals and Insulin), la rotation de l'écran vertical -> horizontal fait basculer sur l'écran de définition d'un nouveau repas

**Comment by jmottet** [comment]
Forcer le mode "portrait".

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by laurel1635** [comment]
OK, à clôturer
