### ISSUE TITLE
Setup de l'application

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#40]
[GluCalc- New Meal - SetUp _V2.pptx](https://github.com/jmottet/GluCalc/files/29195/GluCalc-.New.Meal.-.SetUp._V2.pptx)

**Comment by jmottet** [comment]
Cet écran est également appelé depuis le menu : "configuration initiale".

**Comment by jmottet** [comment]
J'ai implémenté l'écran pour sélectionner une unité de mesure de glycémie (accès par le menu "Configuration Initiale").

**Comment by jmottet** [comment]
Pour la "Configuration Initiale", il faudrait un bouton "Vu (OK)" pour valider le changement.

**Comment by jmottet** [comment]
Le message de warning "La saisie des paramètres..." ne devrait s'afficher que durant la phase de "Setup" et non durant la "Configuraiton initiale".

**Comment by laurel1635** [comment]
Step 1/3 - Accepter les conditions d'utilisation (cf. txt FR/EN dans issue #35 )
Step 2/3 - Sélectionner l'unité de mesure de la glycémie
Step 3/3 - Popup
Création d'un type de repas
GluCalc fonctionne correctement, lorsque vous configurez des types de repas avec les conseils de l'équipe médicale
Define Meal Type
GluCalc run correctly when you define meal types with medical team supervision

Créer/Create -> rediriger vers Paramètres\Repas & Insuline\+
Annuler/Cancel -> rediriger vers Nouveau repas

**Comment by jmottet** [comment]
Implémentation effectué

**Comment by laurel1635** [comment]
1) Supprimer le no de version dans cet écran
2) Reprendre la couleur grise du bandeau standard

![screenshot_2016-04-28-21-42-32_resized](https://cloud.githubusercontent.com/assets/8920509/14899716/ac0789d6-0d8d-11e6-890b-a4a153b55d66.png)

**Comment by jmottet** [comment]
Correction effectuée. A voir si ça convient.

**Comment by laurel1635** [comment]
OK
