### ISSUE TITLE
Saisie des nombres

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#41]
Corriger la saisie des nombres
- Lors de la première insertion - reset de la cellule et saisie des entiers
- Lors de la modification - possibilité de reset de la cellule ou modification du nombre existant

**Comment by laurel1635** [comment]
[GluCalc – Saisie d’un nombre.docx](https://github.com/jmottet/GluCalc/files/102428/GluCalc.Saisie.d.un.nombre.docx)
Voici un fichier décrivant le comportement souhaité des champs numériques. Je cherche une solution pour te prêter un autre Ipod/Iphone

**Comment by laurel1635** [comment]
1) Le calcul de la quantité (champ du haut) ne fonctionne pas en cas de saisie dans le champ Glucides (champ du bas)
2) Si valeur vide dans le champ opposé à la saisie, le calcul ne fonctionne pas
3) L'affichage de l'icône "croix"  ne devrait pas s'afficher simultanément au texte "saisir une quantité", ce devrait être soit la croix soit le texte.
4) Corriger le libellé "Glucide" par "Glucides" dans l'écran de saisie de l'Aliment (version F)
5) Corriger le libellé "Carbohydrate" par "Carbohydrates" dans l'écran de saisie de l'Aliment (version E)

**Comment by jmottet** [comment]
Les 5 points mentionnés sont corrigés.

J'ai également reproduis le même comportement dans l'écran d'édition "Aliments Favoris".

**Comment by laurel1635** [comment]
Ok sur les 5 points. C'est parfait.
Il reste un petit détail : le reset du champ avec l'icône de la croix est difficile à actionner (je dois avoir des trop gros doigts...)

**Comment by laurel1635** [comment]
2 Bugs lors de la saisie des quantités d'aliment
P. ex : Pâtes cuites
1) Valeur saisie 6, affichage 5.98
2) Problème de repositionnement du curseur pendant la frappe -> risque d'erreur de saisie

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by laurel1635** [comment]
Excellent, ça marche tiptop, Théo a pu tester et valider ;-)
