### ISSUE TITLE
Suppression d'un aliment d'un repas

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#44]
Créer un repas avec plusieurs aliments.

La suppression d'un seul aliment entraine la disparition à l'écran de la totalité des aliments.

Si on relance le repas depuis le premier écran (Type de repas et glycémie), le passage au second écran affiche alors les aliments restants de manière correcte

**Comment by jmottet** [comment]
Je n'ai pas réussi à reproduire ce bug. Si je supprime un aliment, celui-ci est bien supprimé et les autres restants sont toujours affichés à l'écran.

**Comment by jmottet** [comment]
Bug reproduit. A traiter.

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by laurel1635** [comment]
OK cela semble stable. Bug à clôturer.

**Comment by jmottet** [comment]
Ok, calcul à relancer lorsqu'on supprime.

**Comment by jmottet** [comment]
Ok, il y a ces deux problèmes à corriger.

**Comment by jmottet** [comment]
Correction effectuée.
