### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#46]
![glucalc_launch image 640x1136_2](https://cloud.githubusercontent.com/assets/8920509/12658446/60576ca2-c609-11e5-9f3d-3a3eb33dd5f3.png)
Introduire le splash screen au lancement de l'application

**Comment by jmottet** [comment]
A afficher pendant 1 seconde (ou 2).

**Comment by jmottet** [comment]
Implémentation effectuée avec une durée de 2 secondes.

**Comment by laurel1635** [comment]
Testé OK
