### ISSUE TITLE
Ecran Repas - Corriger traduction

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#47]
Remplacer le terme Quantity dans la version française par Quantité
![31728801766188screenshot_2016-02-04-21-58-32](https://cloud.githubusercontent.com/assets/8920509/12829627/763e2952-cb8b-11e5-8681-7ad6f6591494.png)

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by laurel1635** [comment]
OK
