### ISSUE TITLE
Suppression de l'affichage du clavier

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#48]
Le clavier ne doit s'afficher que lorsque l'on clique dans un champ éditable. Il ne doit pas être affiché par défaut, en particulier sur les écrans suivants:
1. Nouveau Repas - Ecran 2 - Saisie du repas
2. Nouveau Repas - Ecran 3 - Ajuster insuline

Sur les autres écrans, le clavier devrait disparaître dès validation/enregistrement de la saisie, en particulier:
1. Aliment - Fiche d'aliment
2. Paramètres - Repas & Insuline - Fiche d'un repas
3. Paramètres - Aliments favoris - Fiche d'un aliment favoris
4. Paramètres - Catégorie d'aliment - Fiche de catégorie

**Comment by jmottet** [comment]
Pour l'instant, j'ai effectué cet écran : 1. Nouveau Repas - Ecran 2 - Saisie du repas

**Comment by jmottet** [comment]
Implémentation effectuée.

**Comment by laurel1635** [comment]
Nickel. Tout est OK !
