### ISSUE TITLE
Delete food Category

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#49]
La suppression d'une catégorie d'aliment (et tous les aliments qu'elle contient) produit un crash si 1 ou plusieurs aliments de cette catégorie sont définis comme aliments favoris.

**Comment by jmottet** [comment]
En cas de suppression d'une catégorie d'aliment, il faut afficher le message suivant si des aliments font partis de cette catégorie : 

**Cette catégorie contient des aliments, cette action va tous les supprimer. Voulez-vous continuer ?**

**Comment by jmottet** [comment]
Lorsqu'on supprime une catégorie d'aliment, les aliments rattachés sont également supprimés.
Néanmoins, si ceux-ci sont présent dans des aliments favoris, l'application "crash".

Il faudrait donc supprimer les aliments favoris lorsqu'on supprime un aliment.

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by laurel1635** [comment]
Testé OK
