### ISSUE TITLE
Delete Meal

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#50]
Suppression d'un repas impossible - crash de l'application

**Comment by jmottet** [comment]
Ceci est dû au fait que j'ai une "foreign key" sur le type de repas au niveau de la table qui gère la prise de repas.

Un changement à ce niveau ne serait pas forcément facile à implémenter si on veut garder le comportement de "sauvegarde intermédiaire" durant la prise du repas.

Je propose de mettre en place un "delete logique". D'un point de vue métier/fonctionnel, ce serait pareil mais d'un point de vue technique ce serait plus approprié.

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by laurel1635** [comment]
Testé OK
