### ISSUE TITLE
Unités de mesures paramétrables - liste des écrans (pour contrôle)

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#51]
New Meal - Screen 1, 2, 3 - OK
![screenshot_2016-03-16-21-09-14_resized](https://cloud.githubusercontent.com/assets/8920509/13828059/eda624f0-ebbf-11e5-88f0-5b75d7a653ad.png)
![screenshot_2016-03-16-21-09-31_resized](https://cloud.githubusercontent.com/assets/8920509/13828070/fc540d8c-ebbf-11e5-8dc3-5db3593e4118.png)
![screenshot_2016-03-16-21-09-38_resized](https://cloud.githubusercontent.com/assets/8920509/13828075/ffc91098-ebbf-11e5-8962-d32b3e29fdcd.png)

Check - Insulin Overview - **KO**
![screenshot_2016-03-16-21-11-26_resized](https://cloud.githubusercontent.com/assets/8920509/13828141/4e209e96-ebc0-11e5-9559-60da15fe9af4.png)

Check - Meal Diary - KO, cf Issue #52 
![screenshot_2016-03-16-21-11-07_resized](https://cloud.githubusercontent.com/assets/8920509/13828179/9037be22-ebc0-11e5-8b04-eac2313bc1be.png)

Settings - Meal and Insulin - OK
![screenshot_2016-03-16-21-11-50_resized](https://cloud.githubusercontent.com/assets/8920509/13828183/94bbe356-ebc0-11e5-886b-0041a26f8945.png)

**Comment by jmottet** [comment]
Correction effectuée.
