### ISSUE TITLE
Meal Diary - Affichage de l'unité de mesure de la glycémie

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#52]
Il manque l'affichage de l'unité de mesure de la glycémie [mmol/l ou mg/dl ou g/l]
![capture](https://cloud.githubusercontent.com/assets/8920509/13828315/3678f008-ebc1-11e5-94f3-245ab0f8ce9e.PNG)

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by laurel1635** [comment]
OK
