### ISSUE TITLE
Journal des repas - Tri dans l'ordre chronologique inverse

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#54]
Tri des repas avec le plus récent au sommet de la liste

![screenshot_2016-03-29-19-05-28_resized_1](https://cloud.githubusercontent.com/assets/8920509/14504895/fe1e9490-01b6-11e6-96d6-8a5050eed2d8.png)

**Comment by jmottet** [comment]
Correction effectuée.

**Comment by laurel1635** [comment]
OK
