### ISSUE TITLE
Aliments par défaut

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#59]
Peupler la base de donnée au moment de l'installation avec des aliments par défaut
Version française
[DefaultFoods-fr.xlsx](https://github.com/jmottet/GluCalc/files/262163/DefaultFoods-fr.xlsx)
English version
[DefaultFoods-en.xlsx](https://github.com/jmottet/GluCalc/files/262165/DefaultFoods-en.xlsx)

**Comment by jmottet** [comment]
Implémentation effectuée.

Note: si français, alors version française. Sinon - quelque soit la langue - version anglaise.

**Comment by laurel1635** [comment]
OK, tiptop
