### ISSUE TITLE
Reset - Créer la fonction

### ISSUE THREAD

**Issue by laurel1635** [jmottet/GluCalc#61]
Créer la fonction Reset  avec les choix non exclusifs suivants : 
[x ] Aliments et catégories / Foods and food categories
[x ] Paramètres des repas / Meals settings
[x ] Journal des repas / Meal diary

**Comment by jmottet** [comment]
Pour les aliments et catégories, proposer avec un message "voulez-vous recharger les aliments par défauts ? Oui / Non"

**Comment by laurel1635** [comment]
1/4) Affichage de l'écran avec une **barre en rouge** (cf. sélection de l'unité de mesure lors de la première installation)

2/4) Modifier le **menu** comme suit
[x ] Aliments et catégories / Foods and food categories
     [x ] Import des données par défaut / Default data import (option cochée par défaut)
[x ] Paramètres des repas / Meals settings
[x ] Journal des repas / Meal diary 

N.B: Toutes les cases sont décochées par défaut à l'exception de l'import des données par défaut.

3/4) Modifier le **message** de confirmation après bouton Reset
Voulez-vous vraiment supprimer les données sélectionnées ?
Annuler - OK
Do you really want to delete the selected data ?
Cancel - OK

4/4) **Décocher** les cases après le Reset
-> déjà OK pour Paramètres des repas et journal des repas
-> KO pour aliments et catégories

**Comment by jmottet** [comment]
Quelques commentaires :
1/4) Comme discuté par téléphone, je laisse la barre en rouge pour l'instant. En effet, ce n'est pas une barre rouge qui se trouve sur l'écran des unités de mesure lors de l'installation mais un texte rouge.

2/4) J'ai ajouté l'élément suivant :
[x ] Import des données par défaut / Default data import

Par contre, j'ai augmenté l'indentation et diminué légèrement la taille de police afin qu'il soit vu comme un sous-élément de : [x ] Aliments et catégories / Foods and food categories.

En outre, je l'ai rendu "cliquable" (et coché par défaut) uniquement lorsque la case des "[x ] Aliments et catégories / Foods and food categories" est coché. Si on décoche "[x ] Aliments et catégories / Foods and food categories", cela a pour effet de décocher "[x ] Import des données par défaut / Default data import" et de le rendre non "cliquable".

3/4) Effectué!

4/4) Je n'ai pas observé de problème au niveau des aliments et catégories. A tester.

**Comment by laurel1635** [comment]
Parfait :-))
